// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Changci: typeof import('./src/components/douyin/zimu/changci/index.vue')['default']
    ChangCiItem: typeof import('./src/components/douyin/zimu/changci/ChangCiItem.vue')['default']
    Changduan: typeof import('./src/components/douyin/zimu/changduan/index.vue')['default']
    ChangDuanItem: typeof import('./src/components/douyin/zimu/changduan/ChangDuanItem.vue')['default']
    Douyin: typeof import('./src/components/douyin/index.vue')['default']
    DyAutoReplyList: typeof import('./src/components/douyin/chat/DyAutoReplyList.vue')['default']
    DyChat: typeof import('./src/components/douyin/chat/DyChat.vue')['default']
    DyChatDropdown: typeof import('./src/components/douyin/chat/DyChatDropdown.vue')['default']
    DyChatItem: typeof import('./src/components/douyin/chat/DyChatItem.vue')['default']
    DyChatList: typeof import('./src/components/douyin/chat/DyChatList.vue')['default']
    DyConfig: typeof import('./src/components/douyin/chat/DyConfig.vue')['default']
    DyFilterSelect: typeof import('./src/components/douyin/chat/DyFilterSelect.vue')['default']
    Dymenu: typeof import('./src/components/douyin/dymenu/index.vue')['default']
    DyReply: typeof import('./src/components/douyin/chat/DyReply.vue')['default']
    DyVideoCssDialog: typeof import('./src/components/douyin/video/DyVideoCssDialog.vue')['default']
    DyVideoForm: typeof import('./src/components/douyin/video/DyVideoForm.vue')['default']
    DyVideoHeader: typeof import('./src/components/douyin/video/DyVideoHeader.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    Emoji: typeof import('./src/components/douyin/emoji/index.vue')['default']
    Icon: typeof import('./src/components/douyin/emoji/icon.vue')['default']
    IconChat: typeof import('./src/components/icon/IconChat.vue')['default']
    IconCss3: typeof import('./src/components/icon/IconCss3.vue')['default']
    IconList: typeof import('./src/components/douyin/emoji/IconList.vue')['default']
    IconMenu: typeof import('./src/components/icon/IconMenu.vue')['default']
    Time: typeof import('./src/components/douyin/time/index.vue')['default']
    Zimu: typeof import('./src/components/douyin/zimu/index.vue')['default']
  }
}
